# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

WORKDIR /app

# Copy source code
COPY . .

# Install dependencies
RUN pip install --no-cache-dir pandas mcp

# Expose nothing (stdio)

# Set entrypoint
ENTRYPOINT ["python", "solo_server.py"]
